CREATE DATABASE Diagram

CREATE TABLE Subjects(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name NVARCHAR(100)  NOT NULL UNIQUE CHECK(LEN(Name)>0)
);

CREATE TABLE Teachers(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name NVARCHAR(MAX) NOT NULL CHECK(LEN(Name)>0),
Salary MONEY NOT NULL CHECK(Salary>=0),
Surname NVARCHAR(MAX) NOT NULL CHECK(LEN(Surname)>0),
);

CREATE TABLE Curators(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name NVARCHAR(MAX) NOT NULL CHECK(LEN(Name)>0),
Surname NVARCHAR(MAX) NOT NULL CHECK(LEN(Surname)>0),
);

CREATE TABLE Faculties(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Financing MONEY NOT NULL CHECK(Financing>0) DEFAULT 0,
Name NVARCHAR(100) NOT NULL CHECK(LEN(Name) >0) UNIQUE,
);

CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Financing MONEY NOT NULL CHECK(Financing >0) DEFAULT 0,
Name NVARCHAR(100) NOT NULL CHECK(LEN(Name) >0) UNIQUE,
FacultyId INT NOT NULL FOREIGN KEY(FacultyId) REFERENCES Faculties(Id)
);

CREATE TABLE Groups(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name NVARCHAR(100) NOT NULL CHECK(LEN(Name) >0) UNIQUE,
Year INT NOT NULL CHECK(Year BETWEEN 1 AND 5),
DepartmentId INT NOT NULL FOREIGN KEY(DepartmentId) REFERENCES Departments(Id)
);

CREATE TABLE GroupsCurators(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
CuratorId INT FOREIGN KEY  (CuratorId) REFERENCES Curators(Id) NOT NULL,
GroupId INT FOREIGN KEY  (GroupId) REFERENCES Groups(Id) NOT NULL,
);

CREATE TABLE Lectures(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ClassRoom NVARCHAR(MAX) NOT NULL CHECK(LEN(ClassRoom) > 0),
SubjectId INT FOREIGN KEY  (SubjectId) REFERENCES Subjects(Id) NOT NULL,
TeacherId INT FOREIGN KEY  (TeacherId) REFERENCES Teachers(Id) NOT NULL,
);

CREATE TABLE GroupLectures(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
GroupId INT FOREIGN KEY  (GroupId) REFERENCES Groups(Id) NOT NULL,
LectureId INT FOREIGN KEY  (LectureId) REFERENCES Lectures(Id) NOT NULL,
);
